#! /bin/sh

set -e

#---------------------------------------------------------------------
#                            post-install                             
# 
# Executed after the package is installed.
#
# http://code.google.com/p/fwtemplates/wiki/PackageHooks
#---------------------------------------------------------------------

case "$1" in
  configure)
    # most recently configured version is $2 (possibly empty string)
    mkdir -p /var/www/html/mondemand/drraw/tmp
    mkdir -p /var/www/html/mondemand/drraw/saved
    mkdir -p /var/www/html/mondemand/data
    chown -R apache:apache /var/www/html/mondemand
    ;;
  *)
    ;;
esac

exit 0
