#! /bin/sh

set -e

#---------------------------------------------------------------------
#                            pre-install                             
# 
# Executed before the package is installed.
#
# http://code.google.com/p/fwtemplates/wiki/PackageHooks
#---------------------------------------------------------------------

case "$1" in
  install)
    mkdir -p /var/www/html/mondemand/data
    mkdir -p /var/www/html/mondemand/drraw/tmp
    mkdir -p /var/www/html/mondemand/drraw/saved
    chown -R apache:apache /var/www/html/mondemand
    ;;
  upgrade)
    # old version is $2
    ;;
  *)
    ;;
esac

exit 0
